[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true
